# 4  NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

In [5]:
%timeit my_arr2 = my_arr * 2

751 μs ± 12 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit my_list2 = [x*2 for x in my_list]

25.3 ms ± 1.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 4.1 The NumPy ndarray: A Multidimensional Array Object

data = np.array([[],[]])

In [7]:
data = np.array([[1.5, -0.1,3], [0,-3, 6.5]])

In [8]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [10]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In the first example, all of the elements have been multiplied by 10. In the second, the corresponding values in each "cell" in the array have been added to each other.

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:

In [20]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [21]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since data2 was a list of lists, the NumPy array arr2 has two dimensions, with shape inferred from the data. We can confirm this by inspecting the ndim and shape attributes:

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

Unless explicitly specified (discussed in Data Types for ndarrays), numpy.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype metadata object; for example, in the previous two examples we have:

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int64')

In addition to numpy.array, there are a number of other functions for creating new arrays. As examples, numpy.zeros and numpy.ones create arrays of 0s or 1s, respectively, with a given length or shape. numpy.empty creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape:

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Caution
It’s not safe to assume that numpy.empty will return an array of all zeros. This function returns uninitialized memory and thus may contain nonzero "garbage" values. You should use this function only if you intend to populate the new array with data.

In [33]:
np.empty((2,3,2))

array([[[0.00000000e+000, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.29441743e-312, 4.47032019e-038]],

       [[4.46553417e-090, 4.91127600e-062],
        [1.52411040e-052, 1.47743128e-075],
        [3.99910963e+252, 1.46030983e-319]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Since NumPy is focused on numerical computing, the data type, if not specified, will in many cases be float64 (floating point).

## Data Types for ndarrays
The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

You can explicitly convert or cast an array from one data type to another using ndarray’s astype method:

In [36]:
arr = np.array([1,2,3,4,5])

In [37]:
arr.dtype

dtype('int64')

In [39]:
float_arr = arr.astype(np.float64)

In [40]:
float_arr

array([1., 2., 3., 4., 5.])

In [41]:
float_arr.dtype

dtype('float64')

In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer data type, the decimal part will be truncated:

In [43]:
arr = np.array([3.7, -1.2, -2.6, .05, 12.9, 10.1])

In [44]:
arr

array([ 3.7 , -1.2 , -2.6 ,  0.05, 12.9 , 10.1 ])

In [45]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

In [47]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)

In [48]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

If casting were to fail for some reason (like a string that cannot be converted to float64), a ValueError will be raised. Before, I was a bit lazy and wrote float instead of np.float64; NumPy aliases the Python types to its own equivalent data types.

You can also use another array’s dtype attribute:

In [49]:
int_array = np.arange(10)

In [50]:
calibers =np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [51]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

There are shorthand type code strings you can also use to refer to a dtype:

In [53]:
zeros_uint32 = np.zeros(8, dtype="u4")

In [54]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

Calling astype always creates a new array (a copy of the data), even if the new data type is the same as the old data type.

## Arithmetic with NumPy Arrays
Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays apply the operation element-wise:

In [55]:
arr = np.array ([[1.,2.,3.], [4.,5.,6.]])

In [56]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [58]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [61]:
1 /arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
arr **2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Comparisons between arrays of the same size yield Boolean arrays:

In [63]:
arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])

In [64]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [65]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Evaluating operations between differently sized arrays is called broadcasting and will be discussed in more detail in Appendix A: Advanced NumPy. Having a deep understanding of broadcasting is not necessary for most of this book.

In [66]:
arr = np.arange(10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

np.int64(5)

In [69]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr[5:8]

array([5, 6, 7])

In [71]:
arr[5:8] = 12

In [72]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcast henceforth) to the entire selection.

An important first distinction from Python's built-in lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

To give an example of this, I first create a slice of arr:

In [73]:
arr_slice = arr[5:8]

In [74]:
arr_slice

array([12, 12, 12])

In [76]:
arr_slice[1] = 12345

In [77]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare" slice [:] will assign to all values in an array:

In [79]:
arr_slice[:] = 64

In [80]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

If you are new to NumPy, you might be surprised by this, especially if you have used other array programming languages that copy data more eagerly. As NumPy has been designed to be able to work with very large arrays, you could imagine performance and memory problems if NumPy insisted on always copying data.

If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array—for example, arr[5:8].copy(). As you will see, pandas works this way, too.

With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [81]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [82]:
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-separated list of indices to select individual elements. So these are equivalent:

In [83]:
arr2d[0][2]

np.int64(3)

In [84]:
arr2d[0,2]

np.int64(3)

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d:

In [85]:
arr3d = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

In [86]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
old_values = arr3d[0].copy()

In [94]:
arr3d[0] =42

In [95]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[0] = old_values

In [98]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a one-dimensional array:

In [99]:
arr3d[1,0]

array([7, 8, 9])

In [100]:
x = arr3d[1]

In [101]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [102]:
x[0]

array([7, 8, 9])

Note that in all of these cases where subsections of the array have been selected, the returned arrays are views.

Caution
This multidimensional indexing syntax for NumPy arrays will not work with regular Python objects, such as lists of lists.

## Indexing with slices
Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

In [103]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [104]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [105]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

As you can see, it has sliced along axis 0, the first axis. A slice, therefore, selects a range of elements along an axis. It can be helpful to read the expression arr2d[:2] as "select the first two rows of arr2d."

In [108]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

When slicing like this, you always obtain array views of the same number of dimensions. By mixing integer indexes and slices, you get lower dimensional slices.
For example, I can select the second row but only the first two columns, like so:

In [109]:
lower_dim_slice = arr2d[1,:2]

Here, while arr2d is two-dimensional, lower_dim_slice is one-dimensional, and its shape is a tuple with one axis size:

In [110]:
lower_dim_slice.shape

(2,)

In [111]:
arr2d[:2,2]

array([3, 6])

Note that a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:

In [113]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [114]:
arr2d[:2,1:] =0

In [115]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing
Let’s consider an example where we have some data in an array and an array of names with duplicates:

In [116]:
names = np.array(["Bob", "Joe", "Will", "Bob","Will", "Joe", "Joe"])

In [118]:
data = np.array([[4,7], [0,2], [-5,6], [0,0], [1,2], [-12,-4], [3,4]])

In [119]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Suppose each name corresponds to a row in the data array and we wanted to select all the rows with the corresponding name "Bob". Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with the string "Bob" yields a Boolean array:

In [120]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [121]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

The Boolean array must be of the same length as the array axis it’s indexing. You can even mix and match Boolean arrays with slices or integers (or sequences of integers; more on this later).

In these examples, I select from the rows where names == "Bob" and index the columns, too:

In [122]:
data[names == "Bob",1:]

array([[7],
       [0]])

In [123]:
data[names == "Bob",1]

array([7, 0])

In [124]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [125]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [126]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

The ~ operator can be useful when you want to invert a Boolean array referenced by a variable:

In [127]:
cond = names == "Bob"

In [128]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [131]:
mask = (names== "Bob") | (names == "Will")

In [132]:
mask

array([ True, False,  True,  True,  True, False, False])

In [133]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

Selecting data from an array by Boolean indexing and assigning the result to a new variable always creates a copy of the data, even if the returned array is unchanged.

```Caution```
The Python keywords and and or do not work with Boolean arrays. Use & (and) and | (or) instead.

Setting values with Boolean arrays works by substituting the value or values on the righthand side into the locations where the Boolean array's values are True. To set all of the negative values in data to 0, we need only do:

In [134]:
data[data < 0 ] = 0

In [135]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [136]:
data[names != "Joe"] = 7

In [137]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had an 8 × 4 array:

In [138]:
arr = np.zeros((8,4))

In [141]:
for i in range(8): arr [i] = i

In [142]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [143]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Hopefully this code did what you expected! Using negative indices selects rows from the end:

In [144]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a one-dimensional array of elements corresponding to each tuple of indices:

In [145]:
arr = np.arange(32).reshape((8,4))

In [146]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [147]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected. The result of fancy indexing with as many integer arrays as there are axes is always one-dimensional.

The behavior of fancy indexing in this case is a bit different from what some users might have expected (myself included), which is the rectangular region formed by selecting a subset of the matrix’s rows and columns. Here is one way to get that:

In [148]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array when assigning the result to a new variable. If you assign values with fancy indexing, the indexed values will be modified:

In [149]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [151]:
arr[[1,5,7,2], [0,3,1,2]] =0

In [152]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and the special T attribute:

In [153]:
arr = np.arange(15).reshape((3,5))

In [154]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

When doing matrix computations, you may do this very often—for example, when computing the inner matrix product using numpy.dot:

In [157]:
arr = np.array([[0,1,0], [1,2,-2], [6,3,2], [-1,0,-1], [1,0,1]])

In [158]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [159]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

The @ infix operator is another way to do matrix multiplication:

In [160]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

Simple transposing with .T is a special case of swapping axes. ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearrange the data: