# 7.1 Handling Missing Data

In [3]:
#7.1 Handling Missing Data

In [4]:
import pandas as pd
import numpy as np

In [5]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [6]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [9]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [10]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [11]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [12]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [13]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [14]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [15]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [18]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [20]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data[4] = np.nan

In [22]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [23]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [25]:
df.iloc[:4, 1] = np.nan

In [26]:
df.iloc[:2, 2] = np.nan

In [27]:
df

0         1         2
0  0.020688       NaN       NaN
1 -0.295131       NaN       NaN
2 -0.946237       NaN -0.210801
3 -1.234509       NaN  0.880501
4  0.305425 -0.761498 -0.129273
5  1.137627 -0.136897  0.971323
6  1.310625 -0.140850  0.334176

In [28]:
df.dropna()

0         1         2
4  0.305425 -0.761498 -0.129273
5  1.137627 -0.136897  0.971323
6  1.310625 -0.140850  0.334176

In [29]:
df.dropna(thresh=2)

0         1         2
2 -0.946237       NaN -0.210801
3 -1.234509       NaN  0.880501
4  0.305425 -0.761498 -0.129273
5  1.137627 -0.136897  0.971323
6  1.310625 -0.140850  0.334176

### Filling In Missing Data

In [30]:
df.fillna(0)

0         1         2
0  0.020688  0.000000  0.000000
1 -0.295131  0.000000  0.000000
2 -0.946237  0.000000 -0.210801
3 -1.234509  0.000000  0.880501
4  0.305425 -0.761498 -0.129273
5  1.137627 -0.136897  0.971323
6  1.310625 -0.140850  0.334176

In [31]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.020688  0.500000  0.000000
1 -0.295131  0.500000  0.000000
2 -0.946237  0.500000 -0.210801
3 -1.234509  0.500000  0.880501
4  0.305425 -0.761498 -0.129273
5  1.137627 -0.136897  0.971323
6  1.310625 -0.140850  0.334176

In [32]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [33]:
df.iloc[2:, 1] = np.nan

In [34]:
df.iloc[4:, 2] = np.nan

In [35]:
df

0         1         2
0  0.358482  0.087027  2.128924
1  0.180602 -0.649156 -0.020213
2 -0.126591       NaN -1.073992
3  0.996521       NaN  1.009956
4 -0.276201       NaN       NaN
5  1.495526       NaN       NaN

In [36]:
df.fillna(method="ffill")

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.358482  0.087027  2.128924
1  0.180602 -0.649156 -0.020213
2 -0.126591 -0.649156 -1.073992
3  0.996521 -0.649156  1.009956
4 -0.276201 -0.649156  1.009956
5  1.495526 -0.649156  1.009956

In [37]:
df.fillna(method="ffill", limit=2)

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.358482  0.087027  2.128924
1  0.180602 -0.649156 -0.020213
2 -0.126591 -0.649156 -1.073992
3  0.996521 -0.649156  1.009956
4 -0.276201       NaN  1.009956
5  1.495526       NaN  1.009956

In [38]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [39]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# 7.2 Data Transformation

### Removing Duplicates

In [40]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],"k2": [1, 1, 2, 3, 3, 4, 4]})

In [41]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [42]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [44]:
data["v1"] = range(7)

In [45]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [46]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [47]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [48]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
"pastrami", "corned beef", "bacon",
"pastrami", "honey ham", "nova lox"],
"ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [49]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [50]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [51]:
data["animal"] = data["food"].map(meat_to_animal)

In [52]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [53]:
def get_animal(x):return meat_to_animal[x]

In [54]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [55]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])


In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [61]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=["Ohio", "Colorado", "New York"],
columns=["one", "two", "three", "four"])

In [62]:
def transform(x):
    return x[:4].upper()

In [63]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [64]:
data.index = data.index.map(transform)

In [65]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [66]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [67]:
data.rename(index={"OHIO": "INDIANA"},columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [68]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [69]:
bins = [18, 25, 35, 60, 100]

In [70]:
age_categories = pd.cut(ages, bins)

In [71]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [72]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [73]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [74]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [75]:
pd.value_counts(age_categories)

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [76]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [77]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [78]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [79]:
data = np.random.uniform(size=20)

In [80]:
pd.cut(data, 4, precision=2)

[(0.011, 0.26], (0.26, 0.5], (0.5, 0.75], (0.26, 0.5], (0.011, 0.26], ..., (0.011, 0.26], (0.011, 0.26], (0.5, 0.75], (0.011, 0.26], (0.75, 0.99]]
Length: 20
Categories (4, interval[float64, right]): [(0.011, 0.26] < (0.26, 0.5] < (0.5, 0.75] < (0.75, 0.99]]

In [81]:
data = np.random.standard_normal(1000)

In [82]:
quartiles = pd.qcut(data, 4, precision=2)

In [83]:
quartiles

[(-3.53, -0.68], (0.69, 3.45], (-3.53, -0.68], (0.033, 0.69], (0.69, 3.45], ..., (0.69, 3.45], (0.69, 3.45], (-3.53, -0.68], (-0.68, 0.033], (0.69, 3.45]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.53, -0.68] < (-0.68, 0.033] < (0.033, 0.69] < (0.69, 3.45]]

In [84]:
pd.value_counts(quartiles)

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.53, -0.68]    250
(-0.68, 0.033]    250
(0.033, 0.69]     250
(0.69, 3.45]      250
Name: count, dtype: int64

In [85]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.5189999999999997, -1.323]    100
(-1.323, 0.0328]                 400
(0.0328, 1.232]                  400
(1.232, 3.452]                   100
Name: count, dtype: int64

### Detecting and Filtering Outliers

In [86]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [87]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021758     0.004810    -0.073622    -0.015743
std       0.990681     0.988869     0.988786     1.018270
min      -2.940240    -3.897363    -4.489497    -2.986856
25%      -0.642604    -0.678113    -0.736278    -0.687486
50%       0.034778     0.006911    -0.071549    -0.074724
75%       0.708267     0.677456     0.608035     0.720390
max       2.836594     3.262856     3.188559     3.243800

In [88]:
col = data[2]

In [89]:
col[col.abs() > 3]

483    3.188559
712   -4.489497
Name: 2, dtype: float64

In [90]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
178  0.482481 -3.897363 -0.097508 -1.251128
267 -0.282283  3.262856 -0.546974 -0.213076
378  1.483646  3.049755 -1.845144  0.154191
483  1.256932  0.644970  3.188559 -0.565421
612  2.330715  1.232879 -0.156999  3.194874
712 -0.318023 -0.607036 -4.489497 -0.334310
753 -1.422047 -3.036306 -0.472123  0.850923
779 -0.188670  0.602125  0.466045  3.243800

In [91]:
data[data.abs() > 3] = np.sign(data) * 3

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021758     0.005431    -0.072321    -0.016182
std       0.990681     0.984628     0.982626     1.016921
min      -2.940240    -3.000000    -3.000000    -2.986856
25%      -0.642604    -0.678113    -0.736278    -0.687486
50%       0.034778     0.006911    -0.071549    -0.074724
75%       0.708267     0.677456     0.608035     0.720390
max       2.836594     3.000000     3.000000     3.000000

In [93]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1  1.0 -1.0  1.0  1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4  1.0  1.0  1.0 -1.0

### Permutation and Random Sampling

In [94]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [95]:
 df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [96]:
sampler = np.random.permutation(5)

In [97]:
sampler

array([1, 0, 3, 4, 2])

In [98]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [99]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [100]:
column_sampler = np.random.permutation(7)

In [101]:
column_sampler

array([0, 6, 4, 1, 2, 3, 5])

In [102]:
df.take(column_sampler, axis="columns")

0   6   4   1   2   3   5
0   0   6   4   1   2   3   5
1   7  13  11   8   9  10  12
2  14  20  18  15  16  17  19
3  21  27  25  22  23  24  26
4  28  34  32  29  30  31  33

In [103]:
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [104]:
choices = pd.Series([5, 7, -1, 6, 4])

In [105]:
choices.sample(n=10, replace=True)

4    4
4    4
1    7
4    4
4    4
2   -1
2   -1
4    4
3    6
4    4
dtype: int64

### Computing Indicator/Dummy Variables

In [106]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})

In [107]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [108]:
pd.get_dummies(df["key"], dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [109]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)

In [110]:
df_with_dummy = df[["data1"]].join(dummies)

In [111]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [112]:
mnames = ["movie_id", "title", "genres"]

In [113]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",header=None, names=mnames, engine="python")

In [114]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [115]:
dummies = movies["genres"].str.get_dummies("|")

In [116]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [117]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [118]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

**Note**
> For much larger data, this method of constructing indicator variables with multiple membership is not especially speedy. It would be better to write a lower-level function that writes directly to a NumPy array, and then wrap the result in a DataFrame.

In [119]:
np.random.seed(12345) # to make the example repeatable

In [120]:
values = np.random.uniform(size=10)

In [121]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [122]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [123]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

### 7.3 Extension Data Types

In [124]:
s = pd.Series([1, 2, 3, None])

In [125]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [126]:
s.dtype

dtype('float64')

In [127]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [128]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [129]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [130]:
s.dtype

Int64Dtype()

In [131]:
s[3]

<NA>

In [132]:
s[3] is pd.NA

True

In [133]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [134]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [135]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [136]:
df = pd.DataFrame({"A": [1, 2, None, 4],"B": ["one", "two", "three", None],
"C": [False, None, False, True]})


In [137]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [138]:
df["A"] = df["A"].astype("Int64")

In [139]:
df["B"] = df["B"].astype("string")

In [140]:
df["C"] = df["C"].astype("boolean")


In [141]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

# 7.4 String Manipulation

### Python Built-In String Object Methods

In [142]:
val = "a,b,  guido"

In [143]:
val.split(",")

['a', 'b', '  guido']

In [144]:
pieces = [x.strip() for x in val.split(",")]

In [145]:
pieces

['a', 'b', 'guido']

In [146]:
first, second, third = pieces

In [147]:
first + "::" + second + "::" + third

'a::b::guido'

In [148]:
"::".join(pieces)

'a::b::guido'

In [149]:
"guido" in val

True

In [152]:
val.index(",")

1

In [153]:
val.find(":")

-1

In [154]:
val.index(":")

ValueError: substring not found

In [155]:
val.count(",")

2

In [156]:
val.replace(",", "::")

'a::b::  guido'

In [157]:
val.replace(",", "")

'ab  guido'

## Regular Expressions

In [158]:
import re

In [176]:
text = "foo    bar\t baz  \tqux"

In [177]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [178]:
regex = re.compile(r"\s+")

In [179]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [180]:
regex.findall(text)

['    ', '\t ', '  \t']

In [181]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [182]:
regex.findall(text)

[' ', '\n', ' ', '\n', ' ', '\n', ' ']

In [183]:
m = regex.search(text)

In [184]:
m

<re.Match object; span=(4, 5), match=' '>

In [185]:
text[m.start():m.end()]

' '

In [186]:
print(regex.match(text))

None


In [187]:
print(regex.sub("REDACTED", text))

DaveREDACTEDdave@google.comREDACTEDSteveREDACTEDsteve@gmail.comREDACTEDRobREDACTEDrob@gmail.comREDACTEDRyanREDACTEDryan@yahoo.com


In [188]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [189]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [190]:
m = regex.match("wesm@bright.net")

In [191]:
m.groups()

('wesm', 'bright', 'net')

In [192]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [223]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))
Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

SyntaxError: invalid syntax (963990853.py, line 2)

# String Functions in pandas

In [224]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com","Rob": "rob@gmail.com", "Wes": np.nan}

In [225]:
data = pd.Series(data)

In [226]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [227]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [228]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [229]:
data_as_string_ext = data.astype('string')

In [230]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [231]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [232]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [233]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [234]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [235]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [236]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [237]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [238]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

# 7.5 Categorical Data

### Background and Motivation

In [239]:
values = pd.Series(['apple', 'orange', 'apple','apple'] * 2)

In [240]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [241]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [242]:
pd.value_counts(values)

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [243]:
values = pd.Series([0, 1, 0, 0] * 2)

In [244]:
dim = pd.Series(['apple', 'orange'])

In [245]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [246]:
dim

0     apple
1    orange
dtype: object

In [247]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Categorical Extension Type in pandas

In [248]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [249]:
N = len(fruits)

In [250]:
rng = np.random.default_rng(seed=12345)

In [251]:
df = pd.DataFrame({'fruit': fruits,'basket_id': np.arange(N),
'count': rng.integers(3, 15, size=N),
'weight': rng.uniform(0, 4, size=N)},
columns=['basket_id', 'fruit', 'count', 'weight'])

In [253]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [254]:
fruit_cat = df['fruit'].astype('category')

In [255]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [256]:
c = fruit_cat.array

In [257]:
type(c)

pandas.core.arrays.categorical.Categorical

In [258]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [259]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [260]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [261]:
df['fruit'] = df['fruit'].astype('category')

In [262]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [263]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [264]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [265]:
categories = ['foo', 'bar', 'baz']

In [266]:
codes = [0, 1, 2, 0, 0, 1]

In [267]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [268]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [269]:
ordered_cat = pd.Categorical.from_codes(codes, categories,ordered=True)

In [270]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [271]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

Computations with Categoricals

In [272]:
rng = np.random.default_rng(seed=12345)

In [273]:
draws = rng.standard_normal(1000)

In [274]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [275]:
bins

[0, 0.2, 0.4, 0.6, 0.8, 1]

In [276]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [277]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [278]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [284]:
bins = pd.Series(bins, name='quartile')

In [285]:
results = (pd.Series(draws).groupby(bins)
.agg(['count', 'min', 'max'])
.reset_index())

/var/folders/5q/z1l12s4n7y1bxgmlhw1vkr7c0000gp/T/ipykernel_10565/2977338057.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = (pd.Series(draws).groupby(bins)


In [286]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [287]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [288]:
N = 10_000_000

In [289]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [290]:
categories = labels.astype('category')

In [291]:
labels.memory_usage(deep=True)

520000132

In [292]:
categories.memory_usage(deep=True)

10000512

In [294]:
%time _ = labels.astype('category')
CPU times: user 279 ms, sys: 6.06 ms, total: 285 ms
Wall time: 285 ms

SyntaxError: invalid syntax (3784706524.py, line 2)

In [295]:
%timeit categories.value_counts()
15.6 ms +- 152 us per loop (mean +- std. dev. of 7 runs, 100 loops each)

SyntaxError: invalid syntax (2048286261.py, line 2)

In [296]:
%timeit categories.value_counts()
15.6 ms +- 152 us per loop (mean +- std. dev. of 7 runs, 100 loops each)

SyntaxError: invalid syntax (2048286261.py, line 2)

### Categorical Methods

In [297]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [298]:
cat_s = s.astype('category')

In [299]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [300]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [301]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [302]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [303]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [304]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [305]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [306]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [307]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [308]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [309]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [310]:
pd.get_dummies(cat_s, dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0